адаптировал под tablet index
alekseyburn/838631-mishka-16 pull request #10
Opened 2019-04-10 23:58 UTC by alekseyburn

2019-04-11 12:02 UTC, KelvinOm requested changes

2019-04-11 12:02 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +  background-size: cover;
Like

2019-04-11 12:02 UTC, KelvinOm commented on source/index.html
> +        <p class="weekly-good__description">Экологически чистая пряжа, ручная&nbsp;работа. Доступны в шести расцветках, и трех размерах.</p>
Все еще не понимаю зачем тебе такие &nbsp; пробелы. Давай созвонимся и ты расскажешь покажешь.

2019-04-11 12:02 UTC, KelvinOm commented on source/index.html
> +            <a class="site-list__link site-list__link--catalog" href="catalog.html">Каталог товаров</a>
Надо переделать шапку. Повесить position: relative; на header, модификаторы ператащить на li(у тебя ссылки сейчас больше чем нужно). Подсказака: у catalog должен быть left: 50px, а у delivery right: 50px; И delivery вроде не ссылка, а отдельный блок.

2019-04-11 12:02 UTC, KelvinOm commented on source/sass/blocks/weekly-good.scss
> +  .weekly-good__img {
Тут тебе нужны обертки.
![2019-04-11_14-41-48](https://user-images.githubusercontent.com/11555074/55955431-1cbdcb80-5c6a-11e9-9c8d-8c1e4fb02105.png)

Одна у тебя уже есть и не используется. Добавить еще одну и картинка сама по себе. См. рисунок

2019-04-11 12:02 UTC, KelvinOm commented on source/sass/blocks/weekly-good.scss
> +    &::after {
В weekly-good проверь zigzag. Что-то надо придумать с высотой. На смежных экранах оно так.
![2019-04-11_14-40-08](https://user-images.githubusercontent.com/11555074/55955505-4ecf2d80-5c6a-11e9-8c62-8cfbebcd4ae7.png)

2019-04-11 12:02 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +  .categories__link {
В categories__link надо выровнять текст, попробуй сделать так же как в radio, логика тут такая же.
![2019-04-11_14-59-36](https://user-images.githubusercontent.com/11555074/55955569-745c3700-5c6a-11e9-918b-b48c0fb41788.png)
![2019-04-11_14-40-20](https://user-images.githubusercontent.com/11555074/55955571-7625fa80-5c6a-11e9-8c13-26cb8bd7ef84.png)

2019-04-12 00:34 UTC, alekseyburn commented
Переделал weekly-good. Посмотрел как тянется этот блок в обзоре на проект, пока не смог разобраться как сделать так же, понял только, что задавать обертке 50% для такого эффекта точно не нужно, а размеры изображения фиксированные.

2019-04-13 19:55 UTC, KelvinOm requested changes

2019-04-13 19:55 UTC, KelvinOm commented on source/sass/blocks/weekly-good.scss
> +  display: block;
Блок у тебя уже есть в общих стилях.

2019-04-13 19:55 UTC, KelvinOm commented on source/index.html
> +      <div class="weekly-good__wrapper weekly-good__wrapper--half">
weekly-good__wrapper тут по смыслу вообще другой враппер и в модификаторе ты полностью его переопределяешь. МБ сделаем два разных враппера и назовем их так, чтобы было понятно, что они делают. half на самом деле не очень семантично.

2019-04-13 19:55 UTC, KelvinOm commented on source/sass/blocks/reviews.scss
> +    width: 50%;
Не очень хорошо тут делать  50%; лучше отпустить заголовок и если будет переполнение, то выравнивать через flex. допустим завтра надо будет написать СуперПупер крутые отзывы наших клиентов и надо будет верстку переделывать.

2019-04-13 19:55 UTC, KelvinOm commented on source/sass/blocks/reviews.scss
> +    width: 20%;
Зачем? Сделай выравнивание через flex и отпусти ширину. Тут точно может быть что-то довольно длинное. Всегда старайся проверять на переполнение

2019-04-13 19:55 UTC, KelvinOm commented on source/sass/blocks/reviews.scss
> +  .reviews__slide-btn {
btn  -> cahnge-btn

2019-04-13 19:55 UTC, KelvinOm commented on source/sass/blocks/reviews.scss
> +  .reviews__slide-btn {
(минор)Выравнивание бы сделать нормальным, мало-ли завтра нужно будет ховер поменять.
![2019-04-13_22-03-45](https://user-images.githubusercontent.com/11555074/56084264-6577af00-5e39-11e9-8214-842671864392.png)

2019-04-13 19:55 UTC, KelvinOm commented on source/catalog.html
>              <img class="catalog__img" width="260" height="195" src="img/photo-toys-mobile@1x.jpg" alt="Большая корзинка для игрушек">
Картинки искажаются. Надо отпустить width и сделать их по центру, а то что вываливается спрятать.

2019-04-13 19:55 UTC, KelvinOm commented on source/catalog.html
>            <div class="catalog__wrapper">
ховер должен быть и под фото
![2019-04-13_22-20-19](https://user-images.githubusercontent.com/11555074/56084324-5cd3a880-5e3a-11e9-9bd9-aee8a9c3a2ef.png)

2019-04-13 19:55 UTC, KelvinOm commented on source/sass/blocks/production.scss
> +    min-height: 455px; // для соответствия высоте. Думаю, что когда будут меняться изображения, то все будет нормально.
min-height надо убрать. Из-за этого у тебя зеленая полоска появляется.
![2019-04-13_22-35-26](https://user-images.githubusercontent.com/11555074/56084514-87befc00-5e3c-11e9-8d66-8f29aba821fd.png)

У `production__img` и `production__link` все стили дропнуть и поставить им display: block. Чтобы этот элемент тянулся под размер содержимого. Так же надо подправить процент в `padding-bottom`

2019-04-13 19:55 UTC, KelvinOm commented on source/sass/blocks/production.scss
> +    min-height: 455px; // для соответствия высоте. Думаю, что когда будут меняться изображения, то все будет нормально.
Для десктопа production__img надо отцентровать и растянуть, чтобы не было зеленого фона.

2019-04-13 19:55 UTC, KelvinOm commented on source/catalog.html
>              <img class="catalog__img" width="260" height="195" src="img/photo-toys-mobile@1x.jpg" alt="Большая корзинка для игрушек">
Для этих картинок надо сделать кадрирование например так:
```
<picture>
  <source media="(min-width: 1200px)" srcset="img/photo-1-desktop.jpg">
  <source media="(min-width: 768px)" srcset="img/photo-1-tablet.jpg">
  <img src="img/photo-1-mobile.jpg" alt="Пример">
</picture>
```

2019-04-14 00:12 UTC, alekseyburn commented on source/sass/blocks/production.scss
> +    min-height: 455px; // для соответствия высоте. Думаю, что когда будут меняться изображения, то все будет нормально.
Не пойму зачем production__img и production__link надо дропать стили, после изменения процента в padding-bottom и убирания мин высоты картинка вроде тянется на 100%. Попробовал стили удалить, но ничего не изменилось.

2019-04-14 00:26 UTC, alekseyburn commented on source/sass/blocks/production.scss
> +    min-height: 455px; // для соответствия высоте. Думаю, что когда будут меняться изображения, то все будет нормально.
Картинка ведь будет меняться в зависимости от версии экрана. Я попробовал вставить туда планшетную версию и увеличить до десктопа. Она тянется хорошо без зеленого фона.

2019-04-14 00:35 UTC, alekseyburn commented on source/sass/blocks/weekly-good.scss
> +  display: block;
Немного не понял. Изображение стало display:block после того как weekly-good задали flex?

2019-04-14 00:39 UTC, alekseyburn commented
Если что, то это не все правки, не успел и лег спать.

2019-04-14 16:16 UTC, alekseyburn commented
![image](https://user-images.githubusercontent.com/41241809/56095861-99121200-5ee9-11e9-8e51-a2990eaa9567.png)
Переделал все отступы, теперь вроде как все нравится (На самом деле я бы переделал шапку, но пусть пока будет как есть). Оставил комментарии с вопросами в коде. Из кроссбраузерности исправил все, что нашел, но в ie11 так и не понял почему ширина у этих вещей не фиксируется и выбивыается.

2019-04-14 17:44 UTC, KelvinOm commented on source/sass/blocks/weekly-good.scss
> +  display: block;
В текущей реализации исправлено.

2019-04-14 17:46 UTC, KelvinOm commented on source/sass/blocks/production.scss
> +    min-height: 455px; // для соответствия высоте. Думаю, что когда будут меняться изображения, то все будет нормально.
Если стили дропнуть и ничего не меняется, то зачем они нужны?

2019-04-14 17:47 UTC, KelvinOm commented on source/catalog.html
>              <img class="catalog__img" width="260" height="195" src="img/photo-toys-mobile@1x.jpg" alt="Большая корзинка для игрушек">
А чего на `picture` не переводишь?

2019-04-14 18:52 UTC, KelvinOm commented on source/catalog.html
> +            <img class="catalog__img" src="img/photo-toys-mobile@1x.jpg" alt="Большая корзинка для игрушек">
width="260" height="195" — зачем дропнул?

http://codeguide.academy/html-css.html#html-img-sizes

2019-04-14 18:52 UTC, KelvinOm commented on source/catalog.html
> +            <img class="catalog__img" src="img/photo-toys-mobile@1x.jpg" alt="Большая корзинка для игрушек">
И далее тоже надо вернуть размеры.

2019-04-14 18:52 UTC, KelvinOm commented on source/sass/blocks/about.scss
> +    // При добавлении нового элемента это не сработает. Используются ли в БЭМе :last-child и подобное? Можно ли как-то правильнее переопределить маргин для последнего элемента в списке?;
last-child используются. Использование псевдоклассов никак не ограничено. Тут все норм.

2019-04-14 18:52 UTC, KelvinOm commented on source/sass/blocks/about.scss
> +  //задал всем иконкам общую высоту, теперь отступы выглядят как в макете(плюс-минус)
:)

2019-04-14 18:52 UTC, KelvinOm commented on source/sass/blocks/catalog.scss
> +  position: relative;
Если хочешь попотеть, то пройдись по своим стилям и подровняй порядок свойств. Делай это отдельным ПР пожалуйста .

http://codeguide.academy/html-css.html#css-order

2019-04-14 18:52 UTC, KelvinOm commented on source/sass/blocks/contacts.scss
>  .contacts__title {
минор
![2019-04-14_21-01-06](https://user-images.githubusercontent.com/11555074/56097496-b7820880-5efd-11e9-8c04-69ecea3147be.png)

2019-04-14 18:52 UTC, KelvinOm commented on source/sass/blocks/catalog.scss
> +    min-height: 197px; // не смог разобраться как сделать их все одинаковой высоты без задания этой высоты.
1) min-height: 197px; -> flex: 1;
2) На десктопной вьюхе надо убрать margin-bottom: 0; у последнего элемента catalog__item.

2019-04-14 18:52 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +  &::before {
Это зачем?

2019-04-14 18:52 UTC, KelvinOm commented on source/sass/blocks/page-footer.scss
> +  &::before {
А это зачем?

2019-04-14 18:52 UTC, KelvinOm commented on source/sass/blocks/weekly-good.scss
> +    //можно ли как-то выорвнять содержимое weekly-good__title-wrapper без задания высоты? align-items в разных значениях не помог.
Не понял о чем ты, но если обнулить `margin-top` и `margin-bottom`, то все хорошо равняется через `align-items: center;` 
![2019-04-14_21-50-11](https://user-images.githubusercontent.com/11555074/56097599-49d6dc00-5eff-11e9-831f-974a7588049e.png)

2019-04-14 18:52 UTC, KelvinOm commented on source/sass/blocks/production.scss
> +    min-height: 455px; // для соответствия высоте. Думаю, что когда будут меняться изображения, то все будет нормально.
И выглядит это все еще так:
![2019-04-14_21-51-37](https://user-images.githubusercontent.com/11555074/56097608-7d196b00-5eff-11e9-974f-d48c66edc2de.png)
![2019-04-14_21-51-55](https://user-images.githubusercontent.com/11555074/56097613-8a365a00-5eff-11e9-907a-5e2cb79f53e4.png)

2019-04-14 18:55 UTC, KelvinOm commented
Почему при наведении на production, у меня тень под всей плашкой, а при наведении на catalog__item тенька есть только у catalog__wrapper?

![2019-04-14_21-55-29](https://user-images.githubusercontent.com/11555074/56097655-0e88dd00-5f00-11e9-8584-709a14889f93.png)

2019-04-14 18:57 UTC, alekseyburn commented on source/catalog.html
>              <img class="catalog__img" width="260" height="195" src="img/photo-toys-mobile@1x.jpg" alt="Большая корзинка для игрушек">
Дак это тема следующей лекции)

2019-04-14 18:59 UTC, KelvinOm commented
А это зачем?
![2019-04-14_21-59-07](https://user-images.githubusercontent.com/11555074/56097691-8fe06f80-5f00-11e9-9915-53511bf8b85d.png)

2019-04-14 18:59 UTC, alekseyburn commented on source/catalog.html
> +            <img class="catalog__img" src="img/photo-toys-mobile@1x.jpg" alt="Большая корзинка для игрушек">
Они ведь все равно не останутся после добавления <picture>?

2019-04-14 19:03 UTC, alekseyburn commented on source/sass/blocks/catalog.scss
> +  position: relative;
В каталоге просто не использовал еще csscomb. Так по сути у меня порядок свойств выстраивается по их кодгайду( по крайней мере файл брал у них из гитхаба)

2019-04-14 19:05 UTC, alekseyburn commented on source/sass/blocks/categories.scss
> +  &::before {
Это фикс для ie чтобы текст выровнялся по центру по вертикали. Ты мне кидал ссылку на stackoverflow.

2019-04-14 19:07 UTC, alekseyburn commented on source/sass/blocks/weekly-good.scss
> +    //можно ли как-то выорвнять содержимое weekly-good__title-wrapper без задания высоты? align-items в разных значениях не помог.
Похоже, что я проморгал какой-то из маргинов, когда пытался задавать ai-c и поэтому у меня не получалось.

2019-04-14 19:08 UTC, alekseyburn commented on source/sass/blocks/page-footer.scss
> +  &::before {
Это декоративное подчеркивание между social и copyright на мобильном устройстве.

2019-04-14 19:10 UTC, alekseyburn commented
> Почему при наведении на production, у меня тень под всей плашкой, а при наведении на catalog__item тенька есть только у catalog__wrapper?
> 
> ![2019-04-14_21-55-29](https://user-images.githubusercontent.com/11555074/56097655-0e88dd00-5f00-11e9-8584-709a14889f93.png)

По стайлгайду я увидел, что тень только под оберткой, поэтому изначально сделал так.

2019-04-14 19:21 UTC, KelvinOm commented on source/catalog.html
> +            <img class="catalog__img" src="img/photo-toys-mobile@1x.jpg" alt="Большая корзинка для игрушек">
Не понял вопрос.  Посмотри ссылку, пожалуйста.

2019-04-14 19:22 UTC, KelvinOm commented on source/sass/blocks/catalog.scss
> +  position: relative;
Ок. Но обрати внимание на это.

2019-04-14 19:22 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +  &::before {
Коммент нужен!

2019-04-14 19:23 UTC, KelvinOm commented on source/sass/blocks/page-footer.scss
> +  &::before {
Хорошо бы для этого display: none прописать на всем что отлично от мобилки.

2019-04-15 18:56 UTC, KelvinOm approved these changes

2019-04-15 18:56 UTC, KelvinOm commented on source/sass/blocks/form.scss
> +      &:nth-child(2n + 1) {
В целом ок. Смотри к таким штукам есть довольно гибкий подход, будет хорошо если ты научишься его использовать.

![2019-04-15_21-50-54](https://user-images.githubusercontent.com/11555074/56157709-df8a6e00-5fc8-11e9-9058-4cf3fddb1039.png)
![2019-04-15_21-49-58](https://user-images.githubusercontent.com/11555074/56157715-e2855e80-5fc8-11e9-9152-8a96a035860d.png)

https://getbootstrap.com/docs/4.0/examples/album/

2019-04-16 10:20 UTC, merged