разметил блоки reviews и contacts в index
alekseyburn/838631-mishka-16 pull request #4
Opened 2019-04-03 18:59 UTC by alekseyburn

2019-04-03 20:11 UTC, KelvinOm requested changes

2019-04-03 20:11 UTC, KelvinOm commented on source/index.html
> +        <img class="map__img" src="#" width="67" height="100" alt="г. Санкт-Петербург, ул. Большая Конюшенная, д. 19/8, офис 101">
(Минор) Это я так понимаю маркер? тебе не надо его тут добавлять, эта штука добавляется через API карт.

2019-04-03 20:11 UTC, KelvinOm commented on source/index.html
> +        <iframe src="https://yandex.ru/map-widget/v1/-/CCu264MZ" width="67" height="100" allowfullscreen="true"></iframe>
(Минор) width="320" height="457"

2019-04-03 22:47 UTC, alekseyburn commented on source/index.html
> +        <img class="map__img" src="#" width="67" height="100" alt="г. Санкт-Петербург, ул. Большая Конюшенная, д. 19/8, офис 101">
Не, это просто изображение карты статическое на случай если карта с яндекса не загрузится по каким-либо причинам.

2019-04-03 22:50 UTC, alekseyburn commented on source/index.html
> +        <iframe src="https://yandex.ru/map-widget/v1/-/CCu264MZ" width="67" height="100" allowfullscreen="true"></iframe>
Посмотрел, да, с размерами ошибся, случайно выделил маркер вместо карты.

2019-04-04 07:54 UTC, KelvinOm commented on source/index.html
> +        <img class="map__img" src="#" width="67" height="100" alt="г. Санкт-Петербург, ул. Большая Конюшенная, д. 19/8, офис 101">
Ок, но тогда ты не правильно проставил размеры.

2019-04-04 08:08 UTC, KelvinOm approved these changes

2019-04-04 10:28 UTC, merged