разметил production в catalog
alekseyburn/838631-mishka-16 pull request #5
Opened 2019-04-03 19:04 UTC by alekseyburn

2019-04-03 20:39 UTC, KelvinOm requested changes

2019-04-03 20:39 UTC, KelvinOm commented on source/catalog.html
> +      <!-- Иконку думаю делать с помощью псевдоэлемента -->
Ок, но нужен модификатор.

2019-04-03 20:39 UTC, KelvinOm commented on source/catalog.html
> +      <!-- Объясняю такую структуру - посмотрел стайлгайд и ТЗ, подумал, что лучше сделать видео по примеру Вадима Макеева https://www.youtube.com/watch?v=4JS70KB9GS0 -->
Хорошее видео, глоток свежего воздуха после энтерпрайз :)

2019-04-03 22:55 UTC, alekseyburn commented on source/catalog.html
> +      <!-- Объясняю такую структуру - посмотрел стайлгайд и ТЗ, подумал, что лучше сделать видео по примеру Вадима Макеева https://www.youtube.com/watch?v=4JS70KB9GS0 -->
Не понял про что идет речь, если можно, то в ЛС поподробнее)

2019-04-03 22:58 UTC, alekseyburn commented on source/catalog.html
> +      <!-- Иконку думаю делать с помощью псевдоэлемента -->
Почему, ведь этот элемент встречается всего один раз в блоке?

2019-04-04 08:07 UTC, KelvinOm commented on source/catalog.html
> +      <!-- Иконку думаю делать с помощью псевдоэлемента -->
Валидно

2019-04-04 08:07 UTC, KelvinOm commented on source/catalog.html
> +      <!-- Объясняю такую структуру - посмотрел стайлгайд и ТЗ, подумал, что лучше сделать видео по примеру Вадима Макеева https://www.youtube.com/watch?v=4JS70KB9GS0 -->
Удали коммент и вливай. Решение по вставке видео хорошее.

2019-04-04 08:07 UTC, KelvinOm approved these changes

2019-04-04 10:32 UTC, merged