разметил форму в form
alekseyburn/838631-mishka-16 pull request #6
Opened 2019-04-03 19:07 UTC by alekseyburn

2019-04-03 20:56 UTC, KelvinOm requested changes

2019-04-03 20:56 UTC, KelvinOm commented on source/form.html
> +                <input class="form__radio visually-hidden" type="radio" name="type" value="Аксессуар для интерьера" checked>Аксессуар для интерьера
На будущее. Для атрибуты лучше отбивку делать.
```
<input
	class="form__radio visually-hidden"
	type="radio"
	name="type"
	value="Аксессуар для интерьера"
	checked>
	Аксессуар для интерьера
```

2019-04-03 20:56 UTC, KelvinOm commented on source/form.html
> +                <input class="form__radio visually-hidden" type="radio" name="type" value="Аксессуар для интерьера" checked>Аксессуар для интерьера
Если решишь так писать, то надо будет править по всему проекту. Так что не делай этого сейчас.

2019-04-03 20:56 UTC, KelvinOm commented on source/form.html
> +                <input class="form__radio visually-hidden" type="radio" name="type" value="Детская игрушка" checked>Детская игрушка
checked тут не нужен

2019-04-03 20:56 UTC, KelvinOm commented on source/form.html
> +                <input class="form__checkbox visually-hidden" type="checkbox" name="White" checked>Белый
checkbox и radio как и кнопку(button) лучше абстрагировать, они могут понадобиться где-нибудь еще. Подумай как это можно сделать.

2019-04-03 23:02 UTC, alekseyburn commented on source/form.html
> +                <input class="form__radio visually-hidden" type="radio" name="type" value="Аксессуар для интерьера" checked>Аксессуар для интерьера
Понял

2019-04-03 23:07 UTC, alekseyburn commented on source/form.html
> +                <input class="form__checkbox visually-hidden" type="checkbox" name="White" checked>Белый
button ведь итак абстрагирована - этот класс используется и на странице index, и в каталоге. Если я правильно понял и это так, то чтобы абстрагировать чекбокс и радио кнопку, то я задам  этим инпутам по классу checkbox и radiobutton и в них запишу стилизацию.

2019-04-03 23:08 UTC, alekseyburn commented on source/form.html
> +                <input class="form__radio visually-hidden" type="radio" name="type" value="Детская игрушка" checked>Детская игрушка
Понял

2019-04-04 08:10 UTC, KelvinOm commented on source/form.html
> +                <input class="form__checkbox visually-hidden" type="checkbox" name="White" checked>Белый
Хотел сказать, что checkbox и radio надо по аналогии с кнопкой сделать.

> задам этим инпутам по классу checkbox и radiobutton и в них запишу стилизацию
Тут не только инпуты нужны но и label.

2019-04-04 11:39 UTC, KelvinOm requested changes

2019-04-04 11:39 UTC, KelvinOm commented on source/form.html
> +              <label class="radio">
`<label class="form__item radio">` - тебе нужно будет управлять позиционированием внутри этого блока

2019-04-04 11:39 UTC, KelvinOm commented on source/form.html
> +              <label class="radio">
Для чекбоксов тоже нужно добавить.

2019-04-04 11:39 UTC, KelvinOm commented on source/form.html
> +              <label class="form__label">
И мы оба совсем забыли про обычные инпуты и textarea, их бы тоже абстрагировать.

2019-04-04 11:40 UTC, KelvinOm commented on source/form.html
> +              <label class="radio">
И если будешь абстрагировать инпуты и textarea не забудь и там использовать общие для формы классы.

2019-04-04 16:00 UTC, KelvinOm approved these changes

2019-04-04 18:35 UTC, merged