Module3 task1 index
alekseyburn/838631-mishka-16 pull request #7
Opened 2019-04-05 16:17 UTC by alekseyburn

2019-04-06 19:06 UTC, KelvinOm requested changes

2019-04-06 19:06 UTC, KelvinOm commented on source/index.html
> +    <section class="weekly-good section-indents">
мб просто section?

2019-04-06 19:06 UTC, KelvinOm commented on source/index.html
> +        <h2 class="weekly-good__title section-title">Вязаные корзинки</h2>
section-title -> section__title

2019-04-06 19:06 UTC, KelvinOm commented on source/index.html
> +        <a class="reviews__write button" href="review.html">Написать</a>
reviews__write тебе вроде не нужен только button

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/about.scss
> +  path {
если у иконки в path спилить fill, то можно будет писать fill сразу в классе и не нужна будет эта вложенность.

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/button.scss
> +  padding: 15px 0 13px;
в макете отступы по 20px, почему у тебя так?

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +  background-size: 169%;
Это зачем?

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +  min-height: 281px;
(минор)почему 281? У меня 283 получилось, что тоже странно :)

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +  padding: 70px 30px;
Тебе нужен только верхний отступ и он 76 px

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +  // padding: 26px 30px 29px;
Таких комментов быть не должно.

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +    background-repeat: no-repeat;
Это можно не писать, у тебя заданы размеры нет места для repeat

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +      top: 23px;
Будет лучше если ты в общих стилях напишешь top: 50%, а тут margin-top: -30px. 30px — половина от высоты иконки.

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +      top: 23px;
Будет лучше если ты в общих стилях напишешь top: 50%, а тут margin-top: -31px. 31px — половина от высоты иконки.

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +    padding-bottom: 32px;
Это зачем? Оно и должно прыгать при ховере?

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/page-header.scss
> +  right: 31px;
тут очевидно должно быть 30px

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/page-header.scss
> +  top: 32px;
Тут тоже хорошо бы выравнивание по центру сделать, через top: 50 и margin-top: -7px; Используй, пожалуйста, этот трюк очень удобно для центрирования. И вроде это значение тут вообще не нужно ты центруешь тут все через flex.

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/section-indents.scss
> +  padding: 30px;
У тебя есть переменная для этого, почему не используешь?

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/section-indents.scss
> +  padding-bottom: 39px;
почему 39?

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/site-list.scss
> +    color: rgba($black, 0.6); //функция opacify почему-то не работает, а transparentize обратная функция
Не понимаю твой коммент, что не работает?

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/site-list.scss
> +  padding: 26px 30px 28px 75px;
Тут бы все через flex заверстать. Очень не хорошо выставлять размеры контейнеру через padding, хрупко это.

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/site-list.scss
> +  padding: 26px 30px 28px 75px;
тут тебе нужен padding-left: 76px; и padding-right: 30px; Задай высоту и позиционирование через flex.

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/site-list.scss
> +  top: 30px;
если через flex сделаешь, то не нужно будет

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/site-list.scss
> +  left: 31px;
Переменная? 30px?

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/site-list.scss
> +//есть ли способ сократить стилизацию для ссылок?очень много лишнего как по мне
не вижу тут лишний стилей,  path разве что

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/social.scss
> +  width: 141px;
у меня 180 получилось

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/social.scss
> +  justify-content: space-between;
like  :)

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/weekly-good.scss
> +  margin-bottom: 6px;
тут только это должно остаться

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/weekly-good.scss
> +  font-size: 25px;
Почему это не в section-title? Вообще не увидел чтобы этот класс был описан.

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/weekly-good.scss
> +  padding-bottom: 10px;
padding-top: 9px; и padding-bottom: 10px; тебя сразу должны настораживать. Сразу есть подозрение что у тебя это не по центру. Сделай тоже через flex.

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/main-nav.scss
> +
(минор)Такого быть не должно, надо следить за чистотой кода. :)

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/blocks/page-footer.scss
> +  padding: 0 59px 20px;
нужен только padding-bottom

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/style.scss
> +
У меня редактор ругается на пустую строку, проверь, пожалуйста.

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/variables.scss
> +$font: "opensans", Arial, sans-serif;
Правильно будет так $font: "Open Sans", "Arial", sans-serif;

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/variables.scss
> +$font: "opensans", Arial, sans-serif;
"Open Sans" надо и в fonts поправить.

2019-04-06 19:06 UTC, KelvinOm commented on source/sass/variables.scss
> +$indent: 30px;
(минор)Для таких переменных хорошо оставлять коммент о том где они используются или давать более емкое название.

2019-04-06 22:40 UTC, alekseyburn commented on source/sass/blocks/about.scss
> +  path {
Запомнил)

2019-04-06 23:07 UTC, alekseyburn commented on source/sass/blocks/button.scss
> +  padding: 15px 0 13px;
Я не знаю, что за парадокс, но с такими отступами кнопка по ПП полностью совпадает.

2019-04-06 23:07 UTC, alekseyburn commented on source/sass/blocks/categories.scss
> +  background-size: 169%;
Равнял картинку по ПП.

2019-04-06 23:22 UTC, alekseyburn commented on source/sass/blocks/categories.scss
> +  min-height: 281px;
Перемерял, рука соскочила. Без рамки 282 получается.

2019-04-06 23:29 UTC, alekseyburn commented on source/sass/blocks/categories.scss
> +  padding: 70px 30px;
А отступы справа и слева чтобы текст не прилипал к краям экрана? 76 пикселей слишком много, по ПП 70 пикселей 1 в 1.

2019-04-06 23:30 UTC, alekseyburn commented on source/sass/blocks/categories.scss
> +    background-repeat: no-repeat;
Перестраховкой делал) Удаляю.

2019-04-06 23:33 UTC, alekseyburn commented on source/sass/blocks/categories.scss
> +      top: 23px;
Это для того, чтобы при изменении высоты элемента картинка оставалась посередине?

2019-04-06 23:35 UTC, alekseyburn commented on source/sass/blocks/categories.scss
> +    padding-bottom: 32px;
В стайлгайде написано, что высота элемента должна увеличиваться в высоту на 6 пикселей и текст смещаться вверх на 6 пикселей. Я бы обсудил.

2019-04-06 23:37 UTC, alekseyburn commented on source/sass/blocks/page-header.scss
> +  right: 31px;
Смотрел по ПП. Поправил, для лучшего вида.

2019-04-06 23:41 UTC, alekseyburn commented on source/sass/blocks/section-indents.scss
> +  padding: 30px;
Не знаю, почему-то посчитал, что создал ее чисто для маргинов)

2019-04-06 23:49 UTC, alekseyburn commented on source/sass/blocks/section-indents.scss
> +  padding-bottom: 39px;
Поправил на 42. 36px от кнопки вниз + 6px высота волны.

2019-04-06 23:50 UTC, alekseyburn commented on source/sass/blocks/site-list.scss
> +    color: rgba($black, 0.6); //функция opacify почему-то не работает, а transparentize обратная функция
Я пытался использовать функцию opacify(color, amount), но она не работает почему-то. Поэтому взял вариант с rgba(color, amount).

2019-04-07 00:00 UTC, alekseyburn commented on source/sass/blocks/site-list.scss
> +  padding: 26px 30px 28px 75px;
Сделал.

2019-04-07 00:04 UTC, alekseyburn commented on source/sass/blocks/site-list.scss
> +  top: 30px;
Иконка тогда попадает в паддинг из родительского элемента и выбивается.

2019-04-07 00:06 UTC, alekseyburn commented on source/sass/blocks/site-list.scss
> +  left: 31px;
Мне кажется, что для top она неуместна, ведь это не отступ, а позиционирование, и если  изменить переменную для отступов, то ведь тогда может съехать иконка.

2019-04-07 00:08 UTC, alekseyburn commented on source/sass/blocks/social.scss
> +  width: 141px;
Не пойму как получилось 180
![image](https://user-images.githubusercontent.com/41241809/55676714-58f7d180-58e2-11e9-812e-f67ab40d05a6.png)

2019-04-07 00:09 UTC, alekseyburn commented on source/sass/blocks/weekly-good.scss
> +  font-size: 25px;
Класс написал и благополучно забыл о нем:)

2019-04-07 00:14 UTC, alekseyburn commented on source/sass/blocks/weekly-good.scss
> +  padding-bottom: 10px;
Почему-то боялся переопределять у таблицы свойство display. Это не влияет на семантику?

2019-04-07 00:18 UTC, alekseyburn commented on source/sass/blocks/page-footer.scss
> +  padding: 0 59px 20px;
Исправил

2019-04-07 00:19 UTC, alekseyburn commented on source/sass/style.scss
> +
Ну я сделал ее для явного разделения между общими стилями и стилями блоков, но если это не нужно, то удаляю.

2019-04-07 10:40 UTC, KelvinOm commented on source/sass/blocks/button.scss
> +  padding: 15px 0 13px;
Посмотри внимательнее, текст у тебя должен быть чуть выше.

2019-04-07 10:41 UTC, KelvinOm commented on source/sass/style.scss
> +
Я тут больше за билд переживаю. В целом отбивка логических блоков строками это хорошо

2019-04-07 11:02 UTC, KelvinOm requested changes

2019-04-07 11:02 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +  padding: 70px 30px;
> А отступы справа и слева. Согласен.

2019-04-07 11:02 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +  padding: 70px 30px;
![2019-04-07_13-42-53](https://user-images.githubusercontent.com/11555074/55682367-3cd44e80-593b-11e9-80c9-0cd66d3fa7fa.png)
Но как быть с этим?

2019-04-07 11:02 UTC, KelvinOm commented on source/sass/blocks/categories.scss
> +    padding-bottom: 32px;
Угу, понял. Тебе надо сделать так чтобы плашки как бы выезжали вверх. А у тебя они двигают пространство вниз. Еще если transition добавить должно красиво получится. Сам разберешься как сделать?

2019-04-07 11:02 UTC, KelvinOm commented on source/sass/blocks/site-list.scss
> +    color: rgba($black, 0.6); //функция opacify почему-то не работает, а transparentize обратная функция
opacify($color, $amount) / fade-in($color, $amount) : Makes a color more opaque. По доке оно не для этого используется, а скорее наоборот. Так что у тебя все верно.

2019-04-07 11:02 UTC, KelvinOm commented on source/sass/blocks/social.scss
> +  width: 141px;
Угу, что-то я перемудрил в zeplin.

2019-04-07 11:02 UTC, KelvinOm commented on source/sass/blocks/social.scss
> +    path {
Это решил не править?

2019-04-07 11:04 UTC, KelvinOm requested changes

2019-04-07 11:04 UTC, KelvinOm commented on source/sass/variables.scss
> +$indent: 30px; //используется для маргинов
(минор)Мб для отступов, а не только для маргинов. И хорошо бы примеры использования дописать. Это я к тому что комменты должны быть понятные. Представь что ты вернешься к проекту через 5 лет и этот коммент тебе ничего не скажет.

2019-04-07 17:41 UTC, KelvinOm approved these changes

2019-04-07 19:43 UTC, merged