выполнил стилизацию каталога
alekseyburn/838631-mishka-16 pull request #8
Opened 2019-04-07 15:37 UTC by alekseyburn

2019-04-07 18:23 UTC, KelvinOm requested changes

2019-04-07 18:23 UTC, KelvinOm commented on source/img/icon-interior.svg
> +    <path fill="#149080" d="M-244.227,18.283c-0.286,0.966-0.245,2.191,0.027,3.639c0.494,2.635,1.687,6.041,2.358,9.67h5.062 c0.696-3.641,1.949-7.05,2.471-9.683c0.287-1.445,0.33-2.66,0.041-3.617c-0.275
Зачем ты fill добавляешь?

2019-04-07 18:23 UTC, KelvinOm commented on source/sass/blocks/catalog.scss
> +  } // здесь не совсем понял по стайлгайду про поведение. Надо обсудить.
вроде все правильно сделал.

2019-04-07 18:23 UTC, KelvinOm commented on source/sass/blocks/catalog.scss
> +  padding: $indent;
тут padding по бокам не нужен. У тебя сейчас ховер работе когда еще на карточку не на вел. А почему ты не хочешь вешать абстрагированный section?

2019-04-07 18:23 UTC, KelvinOm commented on source/sass/blocks/catalog.scss
> +  height: 195px; //сделал размеры ссылке потому что заметил, что у ссылки размер по высоте немного больше, чем размер у ее дочернего элемента. Не знаю как с этим бороться, кроме как таким способом.
> у ссылки размер по высоте немного больше
Потому что внутри у тебя img у которой дефлотный `display: inline-block;` и поэтому добавляется отступ, так как технически это получается "буква". Для img надо добавить `display: block;` и все будет хорошо.

2019-04-07 18:39 UTC, alekseyburn commented on source/img/icon-interior.svg
> +    <path fill="#149080" d="M-244.227,18.283c-0.286,0.966-0.245,2.191,0.027,3.639c0.494,2.635,1.687,6.041,2.358,9.67h5.062 c0.696-3.641,1.949-7.05,2.471-9.683c0.287-1.445,0.33-2.66,0.041-3.617c-0.275
Я скорее всего забыл его удалить или запутался с копиями.

2019-04-08 20:43 UTC, KelvinOm requested changes

2019-04-08 20:43 UTC, KelvinOm commented on source/img/icon-toy.svg
> +  <path fill="#149080" d="M226.001,269.871l27.438,15.934v-23.346l-27.438-15.94V269.871z M277.347,238.627v2.453 c0,1.817-3.458,3.29-7.73,3.29c-4.266,0-7.727-1.473-7.727-3.29v-4.059h0.024c0.26,1.714,3.
fill решил не удалять?

2019-04-08 20:43 UTC, KelvinOm commented on source/sass/blocks/catalog.scss
> +  height: 195px;
Тебе эти размеры будут мешать. Надо для картинки добавить display: block; а это спилить.

2019-04-08 20:43 UTC, KelvinOm commented on source/sass/blocks/catalog.scss
> +  // padding-bottom: 0;
Это тут зачем?

2019-04-08 21:04 UTC, merged